---
- hosts: all
  become: True
  remote_user: ec2-user

  tasks:
    - name: install and remove packages with manager `yum`
      block:
      - yum:
          name:
            - java-1.7.0-openjdk
          state: removed
      - yum:
          name:
            - aws-cli
            - amazon-efs-utils
            - curl
            - docker
            - "@development"
            - gcc
            - htop
            - java-1.8.0-openjdk-devel
            - make
            - mlocate
            - parallel
            - pigz
            - tree
            - wget
            - zlib-devel
            - zsh
          state: present

    - name: tell GNU parallel you will cite
      become: False
      block: 
      - file:
          path: '~/.parallel'
          state: directory
          group: "{{ ansible_ssh_user }}"
          owner: "{{ ansible_ssh_user }}"
          mode: 0775
      - copy:
          content: ''
          dest: '~/.parallel/will-cite'
          force: no
          group: "{{ ansible_ssh_user }}"
          owner: "{{ ansible_ssh_user }}"
          mode: 664

    - name: "add user to group `docker` and set the shell to `zsh`"
      user:
        name: "{{ ansible_ssh_user }}"
        shell: /bin/zsh
        groups: docker
        append: yes
