---
- hosts: all
  become: True
  remote_user: ec2-user
  become_user: ec2-user

  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: Install all managed packages
      yum: name={{ item }} state=latest
      with_lines: cat packages
      when: ansible_os_family == "RedHat"
